# Generated by Django 4.1 on 2024-06-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='movimiento',
            field=models.CharField(default='Sin movimiento', max_length=100),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('personajes', models.ManyToManyField(blank=True, to='lol.personaje')),
            ],
        ),
    ]
