# Generated by Django 4.1 on 2024-06-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0003_rename_nombre_personaje_name_rename_nombre_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
