# Generated by Django 4.1 on 2024-06-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0007_skin_user_skins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='fuerza',
        ),
        migrations.AddField(
            model_name='personaje',
            name='linea',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='movimiento',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
